# general configuration
url: http://hwoihann.github.io
baseurl: ''
paginate: 5
paginate_path: "/blog/page:num/"

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/compass.png"
  me: "/images/2017-March"
  # author will appear under the avatar (optional)
  author: "Huihan"  
  title: "2<font siez=4><sup>nd</sup></font>Learn"  

# tagline will appear under the title (optional)
  tagline: "<p>
Daily life: <a href='https://hwoihann.github.io/rethink'>日常部</a><br>
Research: <a href='https://hwoihann.github.io/farnorth'>修炼篇</a><br>
<a href='https://hwoihann.github.io/wiki2gether'>Wiki with Yoyo</a></p>"

 # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true
  
  ##2017-09-24 added personal information link
  person_url: "abt"


#Personal information
github_username: Hwoihann



# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
